% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 18-Nov-2015 18:41:21
%
% This script assumes these variables are defined:
%
%   x - input data.
%   vol - target data.

clear;
load('round2TDailyData.mat');

x=table2array(round2TDailyData(:,[2 7 8 9]))';
t=table2array(round2TDailyData(:,end))';
time=datetime(table2array(round2TDailyData(:,1)));

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainbr';  % Bayesian Regularization backpropagation.

% Create a Fitting Network
hiddenLayerSize = 1;
net = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)

%mape
rowsInTest=tr.testInd';

inputTestVol = t(:,rowsInTest);
outputTestVol = y(:,rowsInTest);
MAPE = mean(abs((outputTestVol-inputTestVol))./inputTestVol)*100;


figure
plot(y);hold all; plot(t)
legend('Predicted','Acutal');
title(strcat('ANN Model','(MAPE=',num2str(MAPE),'%)'));
ylabel('Gas Consumption (kWh)')

save('round2SimpleANNFinal','net')
%% 
load('round2SimpleANNFinal.mat')
load('round2TestDailyData.mat');
x1=table2array(round2TestDailyData(:,[2 7 8 9]))';
y=table2array(round2TestDailyData(:,end));

view(net);
x2 = preparets(net,x1);
yc = net(x2);

ys=smooth(cell2mat(yc));

MAPEactual = mean((abs(cell2mat(yc)'-y)./y)*100);
MAPEactual2=mean((abs(ys-y)./y)*100);

figure
plot(cell2mat(yc)','b');hold all; plot(y,'g');plot(ys,'r');
legend('Predicted','Acutal');
title(strcat('ANN Model','(MAPE Acutal Smoothed=',num2str(MAPEactual2),'%)'));
ylabel('Gas Consumption (kWh)')